### ISSUE TITLE
Riak with aws-java-sdk  (java.net.SocketTimeoutException: Read timed out)

### ISSUE THREAD

**Issue by Efficeon** [basho/riak_cs#1353]
Hello,
Could you help me with problem? I use aws-java-sdk.

```
 @PostConstruct
    private void initializeAmazon() {
        ClientConfiguration opts = new ClientConfiguration();
        opts.setSignerOverride("S3SignerType");  // NOT "AWS3SignerType"
        AmazonS3 s3 = new AmazonS3Client(new BasicAWSCredentials(accessKey, secretKey), opts);
        S3ClientOptions options = new S3ClientOptions();
        options.setPathStyleAccess(true);
        s3.setS3ClientOptions(options);
        s3.setEndpoint(endpointUrl);
        this.s3client = s3;
    }
```
```
private void uploadFileTobucket(String fileName, File file) {
        s3client.putObject(new PutObjectRequest(bucketName, fileName, file)
                .withCannedAcl(CannedAccessControlList.PublicRead));
    }
```
But when I upload file I get a pause and then an exception:
```
java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method) ~[?:1.8.0_191]
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116) ~[?:1.8.0_191]
	at java.net.SocketInputStream.read(SocketInputStream.java:171) ~[?:1.8.0_191]
	at java.net.SocketInputStream.read(SocketInputStream.java:141) ~[?:1.8.0_191]
	at org.apache.http.impl.io.AbstractSessionInputBuffer.fillBuffer(AbstractSessionInputBuffer.java:161) ~[httpcore-4.4.9.jar:4.4.9]
	at org.apache.http.impl.io.SocketInputBuffer.fillBuffer(SocketInputBuffer.java:82) ~[httpcore-4.4.9.jar:4.4.9]
	at org.apache.http.impl.io.AbstractSessionInputBuffer.readLine(AbstractSessionInputBuffer.java:278) ~[httpcore-4.4.9.jar:4.4.9]
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:138) ~[httpclient-4.5.5.jar:4.5.5]
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56) ~[httpclient-4.5.5.jar:4.5.5]
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259) ~[httpcore-4.4.9.jar:4.4.9]
	at org.apache.http.impl.AbstractHttpClientConnection.receiveResponseHeader(AbstractHttpClientConnection.java:286) ~[httpcore-4.4.9.jar:4.4.9]
	at org.apache.http.impl.conn.DefaultClientConnection.receiveResponseHeader(DefaultClientConnection.java:257) ~[httpclient-4.5.5.jar:4.5.5]
	at org.apache.http.impl.conn.ManagedClientConnectionImpl.receiveResponseHeader(ManagedClientConnectionImpl.java:207) ~[httpclient-4.5.5.jar:4.5.5]
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273) ~[httpcore-4.4.9.jar:4.4.9]
	at com.amazonaws.http.protocol.SdkHttpRequestExecutor.doReceiveResponse(SdkHttpRequestExecutor.java:66) ~[aws-java-sdk-core-1.10.39.jar:?]
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125) ~[httpcore-4.4.9.jar:4.4.9]
	at org.apache.http.impl.client.DefaultRequestDirector.tryExecute(DefaultRequestDirector.java:684) ~[httpclient-4.5.5.jar:4.5.5]
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:486) ~[httpclient-4.5.5.jar:4.5.5]
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:835) ~[httpclient-4.5.5.jar:4.5.5]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) ~[httpclient-4.5.5.jar:4.5.5]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56) ~[httpclient-4.5.5.jar:4.5.5]
	at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:822) ~[aws-java-sdk-core-1.10.39.jar:?]
	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:576) [aws-java-sdk-core-1.10.39.jar:?]
	at com.amazonaws.http.AmazonHttpClient.doExecute(AmazonHttpClient.java:362) [aws-java-sdk-core-1.10.39.jar:?]
	at com.amazonaws.http.AmazonHttpClient.executeWithTimer(AmazonHttpClient.java:328) [aws-java-sdk-core-1.10.39.jar:?]
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:307) [aws-java-sdk-core-1.10.39.jar:?]
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3649) [aws-java-sdk-s3-1.10.39.jar:?]
	at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1414) [aws-java-sdk-s3-1.10.39.jar:?]
```

**Comment by Bob-The-Marauder** [comment]
What happens if you try directly with s3cmd? I'd like to first establish whether this is a Riak CS issue or a client issue.
When using s3cmd, remember to use one of the version 1.x releases and set signature_v2 to true in your .s3cfg

**Comment by Efficeon** [comment]
The server had files validation. When downloading some files, the connection went to sleep. That was the problem.  Disabling validation resolved the problem.
