### ISSUE TITLE
aws-sdk-for-ruby can't create a bucket.

### ISSUE THREAD

**Issue by ksauzz** [basho/riak_cs#316]
When aws-sdk-for-ruby sends a create bucket request, it contains empty Content-Type header.  But RiakCS can't parse the request and raise exception. According to [RFC 2616](http://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2), Http header field-value is optional field. So I think RiakCS should work even if it receives empty Content-Type.
#### to reproduce

use this script.  https://gist.github.com/20f671195a836a032d40
#### error messages in ruby

```
% ruby test.rb
/Users/kazuhiro/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/aws-sdk-1.6.10.beta/lib/aws/core/client.rb:318:in `return_or_raise': <html><head><title>500 Internal Server Error</title></head><body><h1>Internal Server Error</h1>The server encountered an error while processing this request</body></html> (AWS::Errors::Base)
        from /Users/kazuhiro/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/aws-sdk-1.6.10.beta/lib/aws/core/client.rb:419:in `client_request'
        from (eval):3:in `create_bucket'
        from /Users/kazuhiro/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/aws-sdk-1.6.10.beta/lib/aws/s3/bucket_collection.rb:113:in `create'
        from test.rb:13:in `<main>'
```
#### error messages on RiakCS

``` erlang
00:44:34.605 [error] webmachine error: path="/simple-bucket/"
[{webmachine_util,media_type_to_detail,1,[{file,"src/webmachine_util.erl"},{line,173}]},
{webmachine_decision_core,accept_helper,0,[{file,"src/webmachine_decision_core.erl"},{line,576}]},
{webmachine_decision_core,decision,1,[{file,"src/webmachine_decision_core.erl"},{line,489}]},
{webmachine_decision_core,handle_request,2,[{file,"src/webmachine_decision_core.erl"},{line,33}]},
{webmachine_mochiweb,loop,1,[{file,"src/webmachine_mochiweb.erl"},{line,89}]},
{mochiweb_http,parse_headers,5,[{file,"src/mochiweb_http.erl"},{line,180}]},{proc_lib,init_p_do_apply,3,
[{file,"proc_lib.erl"},{line,227}]}]
```
#### http trace

```
% sudo http_trace -f "tcp port 8080" --bodies --headers -i lo0
Password:
WARNING: don't use IOWatcher, it'll be removed in v0.9
Listening on lo0
00:44:34.548 127.0.0.1:54444 -> 127.0.0.1:8080 #1 HTTP 1.1 request: PUT http://simple-bucket.s3.amazonaws.com/
    Content-Type:
    User-Agent: aws-sdk-ruby/1.6.10.beta ruby/1.9.3 x86_64-darwin12.0.0
    Date: Tue, 30 Oct 2012 00:44:34 +0900
    Authorization: AWS NQR5J_9GICYRLWEBIYUO:x3aEz9vQSVb7ym/8bKJrClmlMgg=
    Accept: */*
    Host: simple-bucket.s3.amazonaws.com
00:44:34.548 127.0.0.1:54444 -> 127.0.0.1:8080 #1 HTTP 1.1 request complete 0B
00:44:34.608 127.0.0.1:8080 -> undefined:54444 #1 HTTP 1.1 response: 500 Internal Server Error
    Server: MochiWeb/1.1 WebMachine/1.9.0 (someone had painted it blue)
    Date: Mon, 29 Oct 2012 15:44:34 GMT
    Content-Type: text/html
    Content-Length: 170
00:44:34.608 127.0.0.1:8080 -> undefined:54444 #1 HTTP 1.1 response body: 170B
<html><head><title>500 Internal Server Error</title></head><body><h1>Internal Server Error</h1>The server encountered an error while processing this request</body></html>
00:44:34.608 127.0.0.1:8080 -> undefined:54444 #1 HTTP 1.1 response complete 170B
```

**Comment by kellymclaughlin** [comment]
This pr will address this: https://github.com/basho/mochiweb/pull/5

**Comment by ksauzz** [comment]
Thank you for the fix :+1:

**Comment by kellymclaughlin** [comment]
Mochiweb change has been merged so closing this issue.
