### ISSUE TITLE
No response body in 404 to the bucket that have never been created once.

### ISSUE THREAD

**Issue by ksauzz** [basho/riak_cs#347]
RiakCS sends no response body in 404 to the bucket that have never been created once.

Official aws ruby client expects a response body in 404. So aws-sdk-ruby's 'bucket.exists?' doesn't work.
#### get a bucket that have never been created once.

request & response

```
09:02:10.989 33.33.33.1:53280 -> 33.33.33.10:8080 #1 HTTP 1.1 request: GET http://s3.amazonaws.com/bbbbbbbbb
    User-Agent: curl/7.24.0 (x86_64-apple-darwin12.0) libcurl/7.24.0 OpenSSL/0.9.8r zlib/1.2.5
    Host: s3.amazonaws.com
    Accept: */*
    Proxy-Connection: Keep-Alive
    Date: Fri, 30 Nov 2012 09:02:10 GMT
    Authorization: AWS QVN3LOEXFBVO5FGMGVKZ:o7bmv8ucmJfAsRjElxF6FwIfPZ8=
09:02:10.997 33.33.33.10:8080 -> 33.33.33.1:53280 #1 HTTP 1.1 response: 404 Not Found
    Server: MochiWeb/1.1 WebMachine/1.9.0 (someone had painted it blue)
    Date: Fri, 30 Nov 2012 09:02:10 GMT
    Content-Type: application/xml
    Content-Length: 0
09:02:10.997 33.33.33.10:8080 -> 33.33.33.1:53280 #1 HTTP 1.1 response complete 0B
```
#### get a bucket that had been created and deleted.

request & response

```
09:02:55.228 33.33.33.1:53299 -> 33.33.33.10:8080 #1 HTTP 1.1 request: GET http://s3.amazonaws.com/bbbbbbbbb
    User-Agent: curl/7.24.0 (x86_64-apple-darwin12.0) libcurl/7.24.0 OpenSSL/0.9.8r zlib/1.2.5
    Host: s3.amazonaws.com
    Accept: */*
    Proxy-Connection: Keep-Alive
    Date: Fri, 30 Nov 2012 09:02:54 GMT
    Authorization: AWS QVN3LOEXFBVO5FGMGVKZ:BR6/565Dc5rtpVLAuLDuH8ZWhjo=
09:02:55.242 33.33.33.10:8080 -> 33.33.33.1:53299 #1 HTTP 1.1 response: 404 Not Found
    Server: MochiWeb/1.1 WebMachine/1.9.0 (someone had painted it blue)
    Date: Fri, 30 Nov 2012 09:02:55 GMT
    Content-Type: application/xml
    Content-Length: 187
09:02:55.243 33.33.33.10:8080 -> 33.33.33.1:53299 #1 HTTP 1.1 response body: 187B
<?xml version="1.0" encoding="UTF-8"?><Error><Code>NoSuchBucket</Code><Message>The specified bucket does not exist.</Message><Resource>/bbbbbbbbb</Resource><RequestId></RequestId></Error>
09:02:55.243 33.33.33.10:8080 -> 33.33.33.1:53299 #1 HTTP 1.1 response complete 187B
```

**Comment by ksauzz** [comment]
### 404 response body comparison table against no such bucket.

<table>
  <thead>
    <tr>
      <th></th><th>never created bucket</th><th>created bucket once</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>RiakCS: GET bucket</td><td>no response body(empty)</td><td>no such bucket of response body.</td>
    </tr>
    <tr>
      <td>AWS: GET bucket</td><td>no such bucket of response body.</td><td>no such bucket of response body.</td>
    </tr>
  </tbody>
</table>

##### expected no such bucket response.

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<Error>
  <Code>NoSuchBucket</Code>
  <Message>The specified bucket does not exist.</Message>
  <Resource>/bbbbbbbbb</Resource>
  <RequestId></RequestId>
</Error>

```

**Comment by slfritchie** [comment]
Kazuhiro, is this PR ready for review?  If yes, please mark the ticket as "ready-to-pull" on the CS kanban board.

**Comment by ksauzz** [comment]
@slfritchie thank you for the advice! I marked the ticket. I would like someone to review.

**Comment by kellymclaughlin** [comment]
+1 to merge. Please make sure to also merge 1.2 into master to make sure the fix propagates.

**Comment by kellymclaughlin** [comment]
I also added an entry for this issue to our `riak_test` regression test reminder issue: https://github.com/basho/riak_cs/issues/305

**Comment by ksauzz** [comment]
kelly, thank you for the review. I see. I will merge 1.2 into master branch.

**Comment by flozano** [comment]
I am seeing the same behavior in RiakCS 1.3.1 (configured thru vagrant) when retrieving a deleted object. AWS Java SDK expects an XML but RiakCS returns nothing, becoming:

```
Caused by: org.xml.sax.SAXParseException: Premature end of file.
    at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:251) ~[na:1.7.0_15]
    at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:300) ~[na:1.7.0_15]
    at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:121) ~[na:1.7.0_15]
    at com.amazonaws.util.XpathUtils.documentFrom(XpathUtils.java:67) ~[aws-java-sdk-1.3.9.jar:na]
    at com.amazonaws.services.s3.internal.S3ErrorResponseHandler.handle(S3ErrorResponseHandler.java:63) ~[aws-java-sdk-1.3.9.jar:na]
    at com.amazonaws.services.s3.internal.S3ErrorResponseHandler.handle(S3ErrorResponseHandler.java:38) ~[aws-java-sdk-1.3.9.jar:na]
    at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:531) ~[aws-java-sdk-1.3.9.jar:na]
```

**Comment by flozano** [comment]
Opened another issue https://github.com/basho/riak_cs/issues/535
