### ISSUE TITLE
List 'directory' timeouts in case of too many objects (need not be printed) in the directory 

### ISSUE THREAD

**Issue by kuenishi** [basho/riak_cs#466]
When we create million objects at `s3://spam/m/` ,
successful listing:

```
$ time s3cmd ls s3://spam/m/
2013-03-05 19:58     12047   s3://spam/m/moriyoshi0.jpg
(..snip)
2013-03-05 19:58     12047   s3://spam/m/moriyoshi999999.jpg

real    92m56.266s
user    10m28.191s
sys     1m29.978s
```

and fails in case of listing upper directory like:

```
$ time s3cmd ls s3://spam/
WARNING: Retrying failed request: /?delimiter=/ ('')
WARNING: Waiting 3 sec...
WARNING: Retrying failed request: /?delimiter=/ ('')
WARNING: Waiting 6 sec...
WARNING: Retrying failed request: /?delimiter=/ ('')
WARNING: Waiting 9 sec...
WARNING: Retrying failed request: /?delimiter=/ ('')
WARNING: Waiting 12 sec...
WARNING: Retrying failed request: /?delimiter=/ ('')
WARNING: Waiting 15 sec...

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please report the following lines to:
   s3tools-bugs@lists.sourceforge.net
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Problem: S3RequestError: Request failed for: /?delimiter=/
S3cmd:   1.5.0-alpha1

Traceback (most recent call last):
  File "/root/v/bin/s3cmd", line 2063, in <module>
    main()
  File "/root/v/bin/s3cmd", line 2004, in main
    cmd_func(args)
  File "/root/v/bin/s3cmd", line 104, in cmd_ls
    subcmd_bucket_list(s3, uri)
  File "/root/v/bin/s3cmd", line 134, in subcmd_bucket_list
    response = s3.bucket_list(bucket, prefix = prefix)
  File "/root/v/local/lib/python2.7/site-packages/S3/S3.py", line 252, in bucket_list
    response = self.bucket_list_noparse(conn, bucket, prefix, recursive, uri_params)
  File "/root/v/local/lib/python2.7/site-packages/S3/S3.py", line 278, in bucket_list_noparse
    response = self.send_request(request, conn = connection)
  File "/root/v/local/lib/python2.7/site-packages/S3/S3.py", line 698, in send_request
    return self.send_request(request, body, retries - 1)
  File "/root/v/local/lib/python2.7/site-packages/S3/S3.py", line 698, in send_request
    return self.send_request(request, body, retries - 1)
  File "/root/v/local/lib/python2.7/site-packages/S3/S3.py", line 698, in send_request
    return self.send_request(request, body, retries - 1)
  File "/root/v/local/lib/python2.7/site-packages/S3/S3.py", line 698, in send_request
    return self.send_request(request, body, retries - 1)
  File "/root/v/local/lib/python2.7/site-packages/S3/S3.py", line 698, in send_request
    return self.send_request(request, body, retries - 1)
  File "/root/v/local/lib/python2.7/site-packages/S3/S3.py", line 700, in send_request
    raise S3RequestError("Request failed for: %s" % resource['uri'])
S3RequestError: Request failed for: /?delimiter=/

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
    Please report the above lines to:
   s3tools-bugs@lists.sourceforge.net
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

real    22m52.258s
user    0m0.116s
sys     0m0.020s
```

Kelly's pull request on s3cmd [https://github.com/s3tools/s3cmd/pull/90] looks related but not sure.

**Comment by kellymclaughlin** [comment]
@kota Any chance to run the failing command again with the `verbose` and `debug` options to `s3cmd`? Also, any error or timeout log info from either `riak_cs` or `riak` you can share to help diagnose this? Thanks.

**Comment by kuenishi** [comment]
Oops, sorry - I forgot reserving such logs and deleted (when deleting them I totally forgot about this issue). I'll try it later, maybe next week.

**Comment by kuenishi** [comment]
I found out this case Riak CS was using Riak EDS 1.2 - and updating to Riak EDS 1.3 to reproduce it, if this is the case for using Riak 1.2 .

**Comment by kuenishi** [comment]
I'm pretty sure that this is solved by Reid's awesome work of list_objects_v2.
