### ISSUE TITLE
python policy test is dependent on boto retry count.

### ISSUE THREAD

**Issue by ksauzz** [basho/riak_cs#521]
boto_test fails if boto's retry counts is 0. It seems RiakCS doesn't handle keep-alive properly.
### to reproduce
1. change `num_reties` to 0 in `~/.boto`
   
   ```
   [Boto]
   num_retries = 0
   ```
2.  run boto_test

_install nose to run single test. `pip install nose`_

```
% nosetests -m 'test_put_policy' client_tests/python/boto_test.py
E
======================================================================
ERROR: test_put_policy (boto_test.BucketPolicyTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/src/riak_cs/client_tests/python/boto_test.py", line 380, in test_put_policy
    self.assertTrue(bucket.set_policy(policy, headers={'content-type':'application/json'}))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/boto/s3/bucket.py", line 1366, in set_policy
    headers=headers)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/boto/s3/connection.py", line 490, in make_request
    override_num_retries=override_num_retries)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/boto/connection.py", line 932, in make_request
    return self._mexe(http_request, sender, override_num_retries)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/boto/connection.py", line 894, in _mexe
    raise e
BadStatusLine: ''
-------------------- >> begin captured logging << --------------------
boto: DEBUG: Using access key provided by client.
boto: DEBUG: Using secret key provided by client.
boto: DEBUG: path=/0c3db765-4c7c-457d-9259-37d24fa24686/
boto: DEBUG: auth_path=/0c3db765-4c7c-457d-9259-37d24fa24686/
boto: DEBUG: Method: PUT
boto: DEBUG: Path: /0c3db765-4c7c-457d-9259-37d24fa24686/
boto: DEBUG: Data:
boto: DEBUG: Headers: {}
boto: DEBUG: Host: 127.0.0.1:8080
boto: DEBUG: establishing HTTP connection: kwargs={'timeout': 5}
boto: DEBUG: Token: None
boto: DEBUG: StringToSign:
PUT


Wed, 03 Apr 2013 15:45:40 GMT
/0c3db765-4c7c-457d-9259-37d24fa24686/
boto: DEBUG: path=/0c3db765-4c7c-457d-9259-37d24fa24686/
boto: DEBUG: auth_path=/0c3db765-4c7c-457d-9259-37d24fa24686/
boto: DEBUG: path=/0c3db765-4c7c-457d-9259-37d24fa24686/?policy
boto: DEBUG: auth_path=/0c3db765-4c7c-457d-9259-37d24fa24686/?policy
boto: DEBUG: Method: DELETE
boto: DEBUG: Path: /0c3db765-4c7c-457d-9259-37d24fa24686/?policy
boto: DEBUG: Data: /?policy
boto: DEBUG: Headers: {}
boto: DEBUG: Host: 127.0.0.1:8080
boto: DEBUG: Token: None
boto: DEBUG: StringToSign:
DELETE


Wed, 03 Apr 2013 15:45:40 GMT
/0c3db765-4c7c-457d-9259-37d24fa24686/?policy
boto: DEBUG: path=/0c3db765-4c7c-457d-9259-37d24fa24686/
boto: DEBUG: auth_path=/0c3db765-4c7c-457d-9259-37d24fa24686/
boto: DEBUG: path=/0c3db765-4c7c-457d-9259-37d24fa24686/?policy
boto: DEBUG: auth_path=/0c3db765-4c7c-457d-9259-37d24fa24686/?policy
boto: DEBUG: Method: PUT
boto: DEBUG: Path: /0c3db765-4c7c-457d-9259-37d24fa24686/?policy
boto: DEBUG: Data:
{"Version":"2008-10-17","Statement":[{"Sid":"Stmtaaa","Effect":"Allow","Principal":"*","Action":["s3:GetObjectAcl","s3:GetObject"],"Resource":"arn:aws:s3:::0c3db765-4c7c-457d-9259-37d24fa24686/*","Condition":{"IpAddress":{"aws:SourceIp":"127.0.0.1/32"}}}]}

boto: DEBUG: Headers: {'content-type': 'application/json'}
boto: DEBUG: Host: 127.0.0.1:8080
boto: DEBUG: Token: None
boto: DEBUG: StringToSign:
PUT

application/json
Wed, 03 Apr 2013 15:45:40 GMT
/0c3db765-4c7c-457d-9259-37d24fa24686/?policy
boto: DEBUG: encountered BadStatusLine exception, reconnecting
boto: DEBUG: establishing HTTP connection: kwargs={'timeout': 5}
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 1 test in 0.094s

FAILED (errors=1)
```

**Comment by shino** [comment]
CS sends FIN after sending HTTP response to request `bucket.delete_policy()`.
But I don't understand yet why CS sends FIN actively.

sequence (mixture of boto/HTTP/TCP):
- boto: create_bucket (HTTP PUT)
- CS: 200 OK
- boto: bucket.delete_policy (HTTP DELETE)
- CS: 200 OK
- CS: sends FIN
- boto: bucket.set_policy (HTTP PUT)
- CS: reads request and sets policy, but can not write to socket (already FIN'ed)
- CS(ERTS?): send RST
- boto: error which kaz described in this issue.

misc:
- CS also sends FIN actively without `num_retries` or `num_retries=1`.
- boto probably retries silently, so an error can not be seen.

**Comment by shino** [comment]
boto sends DELETE request with body (`/?policy`) and Content-Length >0.

Webmachine does not read body when DELETE, so mochiweb closes socket because it's unsafe to keep alive with remaining bytes.

**Comment by shino** [comment]
https://github.com/basho/webmachine/pull/142
