### ISSUE TITLE
404 has no body when retriving a deleted object

### ISSUE THREAD

**Issue by flozano** [basho/riak_cs#535]
RiakCS 1.3.1 (configured thru vagrant). 

When retrieving a deleted object, AWS Java SDK expects an XML but RiakCS returns nothing, becoming:

```
Caused by: org.xml.sax.SAXParseException: Premature end of file.
    at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:251) ~[na:1.7.0_15]
    at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:300) ~[na:1.7.0_15]
    at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:121) ~[na:1.7.0_15]
    at com.amazonaws.util.XpathUtils.documentFrom(XpathUtils.java:67) ~[aws-java-sdk-1.3.9.jar:na]
    at com.amazonaws.services.s3.internal.S3ErrorResponseHandler.handle(S3ErrorResponseHandler.java:63) ~[aws-java-sdk-1.3.9.jar:na]
    at com.amazonaws.services.s3.internal.S3ErrorResponseHandler.handle(S3ErrorResponseHandler.java:38) ~[aws-java-sdk-1.3.9.jar:na]
    at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:531) ~[aws-java-sdk-1.3.9.jar:na]
```

**Comment by slfritchie** [comment]
Can this bug be closed?

**Comment by kellymclaughlin** [comment]
I think it is still valid, but I am working on a set of changes right now that should address it. I will verify and close this after it is merged.

**Comment by kellymclaughlin** [comment]
[This](https://github.com/basho/riak_cs/pull/578) PR should address this issue.

**Comment by kellymclaughlin** [comment]
This has been resolved.
