### ISSUE TITLE
Riak-CS: cannot list buckets with files in them using s3cmd (had similar issue with AWS Java SDK and DragonDisk too)

### ISSUE THREAD

**Issue by siddhuwarrier** [basho/riak_cs#584]
Hi,

I created some buckets on my local Riak CS cluster (one node running Riak, Riak CS, and Stanchion). I then uploaded some files into them. Then, when I ran the command `s3cmd ls` (or similar, in the case of the AWS Java SDK), Riak CS failed. Let me illustrate using s3cmd as an example:

```
$ s3cmd mb s3://dingdong
$ s3cmd ls #No errors here
$ s3cmd put README.md s3://dingdong
$ s3cmd ls
$s3cmd ls s3://dingdong
WARNING: Retrying failed request: /?delimiter=/ ('')
WARNING: Waiting 3 sec...
WARNING: Retrying failed request: /?delimiter=/ ('')
....
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
An unexpected error has occurred.
Please report the following lines to:
s3tools-bugs@lists.sourceforge.net
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Traceback (most recent call last):
  File "/usr/local/bin/s3cmd", line 2006, in <module>
      main()
    File "/usr/local/bin/s3cmd", line 1950, in main
      cmd_func(args)
    File "/usr/local/bin/s3cmd", line 125, in cmd_ls
      subcmd_bucket_list(s3, uri)
    File "/usr/local/bin/s3cmd", line 155, in subcmd_bucket_list
      response = s3.bucket_list(bucket, prefix = prefix)
    File "/usr/local/Cellar/s3cmd/1.0.1/libexec/S3/S3.py", line 186, in bucket_list
      response = self.bucket_list_noparse(bucket, prefix, recursive, uri_params)
    File "/usr/local/Cellar/s3cmd/1.0.1/libexec/S3/S3.py", line 210, in bucket_list_noparse
      response = self.send_request(request)
    File "/usr/local/Cellar/s3cmd/1.0.1/libexec/S3/S3.py", line 487, in send_request
      return self.send_request(request, body, retries - 1)
    File "/usr/local/Cellar/s3cmd/1.0.1/libexec/S3/S3.py", line 487, in send_request
      return self.send_request(request, body, retries - 1)
    File "/usr/local/Cellar/s3cmd/1.0.1/libexec/S3/S3.py", line 487, in send_request
      return self.send_request(request, body, retries - 1)
    File "/usr/local/Cellar/s3cmd/1.0.1/libexec/S3/S3.py", line 487, in send_request
      return self.send_request(request, body, retries - 1)
    File "/usr/local/Cellar/s3cmd/1.0.1/libexec/S3/S3.py", line 487, in send_request
      return self.send_request(request, body, retries - 1)
    File "/usr/local/Cellar/s3cmd/1.0.1/libexec/S3/S3.py", line 489, in send_request
      raise S3RequestError("Request failed for: %s" % resource['uri'])
  S3RequestError: Request failed for: /?delimiter=/
```

The error from DragonDisk is even more perplexing. See the attached image.

![screen shot 2013-06-05 at 19 55 18](https://f.cloud.github.com/assets/184688/614004/7ba32f5c-ce11-11e2-92dc-078a61230e44.png)

I'd be happy to do any extra debugging if you'd like me to. As of now, the only solution I have is to delete the entire contents of the Riak /data folder, which is obviously not ideal.

**Comment by hectcastro** [comment]
Hey @siddhuwarrier,

Shoot me your Riak, Riak CS, and Stanchion `app.config` files to hector@basho.com and I'll take a look.

**Comment by siddhuwarrier** [comment]
Thanks, @hectcastro , I've emailed you. 

Cheers,

Siddhu

**Comment by siddhuwarrier** [comment]
Thanks for helping me sorting this out, @hectcastro, it was clearly a PICNIC problem. I'll mark this issue as closed. Sorry for the bother! :-)

**Comment by nonsense** [comment]
@siddhuwarrier what was the issue on your side? I am seeing similar behavior and maybe I made the same error..
